name: digital_wallet
description: "OID4VC Digital Identity Wallet Application."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

workspace:
  - packages/tw_crypto
  - packages/tw_iso18013_data_model
  - packages/tw_iso18013_data_transfer
  - packages/tw_iso18013_security
  - packages/tw_logging
  - packages/tw_openid4vci
  - packages/tw_presentation_exchange
  - packages/tw_siop_openid4vp
  - packages/tw_wallet_kit
  - packages/tw_wallet_storage

dependencies:
  app_links: ^6.3.3
  blur: ^4.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.10
  freezed_annotation: ^3.0.0
  go_router: ^15.0.0
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  no_screenshot: ^0.3.1
  package_info_plus: ^8.1.2
  pretty_dio_logger: ^1.4.0
  recase: ^4.1.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.4
  slang: ^4.2.1
  slang_flutter: ^4.2.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

  # Trusted Web packages
  tw_logging:
    path: packages/tw_logging
  tw_wallet_storage:
    path: packages/tw_wallet_storage
  tw_crypto:
    path: packages/tw_crypto

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_flavorizr: ^2.2.3
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  go_router_builder: ^2.7.1
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  slang_build_runner: ^4.4.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    exclude:
      - env/**
      - assets/images/app/**

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/color/colors.xml

  fonts:
    enabled: false
    outputs:
      class_name: AppFonts

import_path_converter:
  ignore_files:
    - \/*\.test.dart
    - \/*\.freezed.dart
    - \/*\.g.dart
    - \/*\.mocks.dart
    - \/*\.gen.dart

import_sorter:
  comments: false
  ignore_files:
    - \/*\.freezed.dart
    - \/*\.g.dart
    - \/*\.mocks.dart
    - \/*\.gen.dart
