name: tw_wallet_storage
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^3.0.0
  tw_crypto:
    path: ../tw_crypto
  tw_iso18013_data_model:
    path: ../tw_iso18013_data_model
  tw_openid4vci:
    path: ../tw_openid4vci
  tw_presentation_exchange:
    path: ../tw_presentation_exchange
  tw_siop_openid4vp:
    path: ../tw_siop_openid4vp
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
