name: tw_iso18013_data_model
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cbor: ^6.3.3
  recase: ^4.1.0
  uuid: ^4.5.1
  tw_crypto:
    path: ../tw_crypto
  tw_logging:
    path: ../tw_logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
