name: tw_openid4vci
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  dio: ^5.7.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  test: ^1.25.8
  very_good_analysis: ^7.0.0
