name: tw_crypto
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  import_path_converter: ^1.0.1

flutter:
  plugin:
    platforms:
      # android:
      #   package: com.dentsusoken.tw_crypto
      #   pluginClass: TwLibCryptoPlugin
      ios:
        pluginClass: TwLibCryptoPlugin
