name: tw_presentation_exchange
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.0

resolution: workspace

# dependencies:

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.0.3
  json_serializable: ^6.9.0
  test: ^1.25.8

assets:
  - assets
